/*
 * Characterization-test harness: runs the REAL ApiRouter (routing, middleware, permission checks, controllers, models,
 * serialization) on an in-memory SQLite database behind a stub login, and records everything the code emits over sockets.
 *
 *   const api = await startApi()          // in beforeEach
 *   const users = await api.seed.users()  // root, admin, user, guest
 *   const res = await api.request('GET', '/api/libraries', { as: 'root' })   // { status, headers, body }
 *   api.emitted                           // [{ method, args }] socket emissions (SocketAuthority is stubbed)
 *   api.watcherCalls                      // [{ method, args }] file-watcher calls (Watcher is stubbed)
 *   await api.stop()                      // in afterEach
 *
 * Managers the router needs (playback sessions, backups, podcasts, ...) are NOT started. Pass fakes via startApi({ managers })
 * and a call to an unconfigured manager throws "manager X not configured", so a test says explicitly what it depends on.
 * Add test data helpers in their own files (helpers/seed-<area>.js); do not edit this file for one test's needs.
 */
const express = require('express')
const cookieParser = require('cookie-parser')
const fs = require('fs')
const os = require('os')
const path = require('path')
const sinon = require('sinon')
const { Sequelize } = require('sequelize')

const Database = require('../../../server/Database')
const Logger = require('../../../server/Logger')
const SocketAuthority = require('../../../server/SocketAuthority')
const Watcher = require('../../../server/Watcher')
const CacheManager = require('../../../server/managers/CacheManager')
const TOKEN_MANAGER_PATH = require.resolve('../../../server/auth/TokenManager')
const ApiRouter = require('../../../server/routers/ApiRouter')
const Auth = require('../../../server/Auth')
const ApiCacheManager = require('../../../server/managers/ApiCacheManager')
const ServerSettings = require('../../../server/objects/settings/ServerSettings')
const fileUpload = require('../../../server/libs/expressFileupload')

// file watching would open real chokidar handles (and keep mocha alive), so Watcher calls are recorded instead
const WATCHER_METHODS = ['initWatcher', 'addLibrary', 'updateLibrary', 'removeLibrary', 'close', 'addIgnoreDir', 'removeIgnoreDir']
const SOCKET_METHODS = ['emitter', 'clientEmitter', 'adminEmitter', 'libraryItemEmitter', 'libraryItemsEmitter']
const MANAGER_NAMES = ['playbackSessionManager', 'abMergeManager', 'backupManager', 'podcastManager', 'audioMetadataManager', 'cronManager', 'emailManager']

const unconfigured = (name) =>
  new Proxy(
    {},
    {
      get: (_, prop) => {
        if (prop === 'then' || typeof prop === 'symbol') return undefined
        throw new Error(`manager ${name} not configured (accessed .${String(prop)}): pass startApi({ managers: { ${name}: {...} } })`)
      }
    }
  )

// Route coverage: ROUTE_COVERAGE=1 ROUTE_COVERAGE_FILE=<path> npm test writes every ApiRouter route and the ones the suite hit
const routeHits = new Map() // route -> Set of status codes seen
let allRoutes = null
let coverageHookInstalled = false
const routeKey = (method, p) => `${method.toUpperCase()} ${p instanceof RegExp ? String(p) : p}`
function listRoutes(expressApp) {
  const out = []
  for (const layer of expressApp._router.stack) {
    if (!layer.route) continue
    for (const m of Object.keys(layer.route.methods)) out.push(routeKey(m, layer.route.path))
  }
  return out
}
function installCoverageHook() {
  if (coverageHookInstalled || process.env.ROUTE_COVERAGE !== '1') return
  coverageHookInstalled = true
  process.on('exit', () => {
    const file = process.env.ROUTE_COVERAGE_FILE
    if (file && allRoutes) fs.writeFileSync(file, JSON.stringify({ all: allRoutes, hits: Object.fromEntries([...routeHits].sort().map(([k, v]) => [k, [...v].sort()])) }, null, 2))
  })
}

function jsonSafe(v) {
  try {
    return JSON.parse(JSON.stringify(v))
  } catch {
    return String(v)
  }
}

/**
 * @param {{ managers?: Record<string, any> }} [opts]
 */
async function startApi(opts = {}) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'abs-char-'))
  const saved = { ServerSettings: global.ServerSettings, ConfigPath: global.ConfigPath, MetadataPath: global.MetadataPath, RouterBasePath: global.RouterBasePath, appRoot: global.appRoot, XAccel: global.XAccel, isWin: global.isWin, AllowCors: global.AllowCors }
  global.ConfigPath = path.join(tmp, 'config')
  global.MetadataPath = path.join(tmp, 'metadata')
  global.RouterBasePath = ''
  global.XAccel = ''
  global.isWin = false
  global.AllowCors = '0'
  fs.mkdirSync(global.ConfigPath, { recursive: true })
  fs.mkdirSync(global.MetadataPath, { recursive: true })

  for (const level of ['info', 'warn', 'error', 'debug', 'dev', 'note']) if (typeof Logger[level] === 'function') sinon.stub(Logger, level)

  Database.sequelize = new Sequelize({ dialect: 'sqlite', storage: ':memory:', logging: false })
  Database.sequelize.uppercaseFirst = (str) => (str ? `${str[0].toUpperCase()}${str.substr(1)}` : '')
  await Database.buildModels()
  const settings = await Database.models.setting.getOldSettings()
  Database.settings = settings.settings
  Database.emailSettings = settings.emailSettings
  Database.notificationSettings = settings.notificationSettings
  Database.serverSettings = settings.serverSettings || new ServerSettings()
  global.ServerSettings = Database.serverSettings.toJSON()

  // Rows created in the same millisecond tie on createdAt, and the server sorts some lists by createdAt (newest episodes, recently
  // added), so the order of tied rows is up to SQLite and flipped between machines. Give auto-generated createdAt/updatedAt values
  // a strictly increasing millisecond so ties cannot happen; explicitly provided timestamps are left alone.
  let lastCreatedAt = 0
  const isAutoNow = (d) => d instanceof Date && Math.abs(d.getTime() - Date.now()) < 2000
  const uniqueNow = (instance) => {
    const attrs = instance.constructor.rawAttributes
    if (!attrs?.createdAt || !isAutoNow(instance.createdAt)) return
    lastCreatedAt = Math.max(Date.now(), lastCreatedAt + 1)
    instance.createdAt = new Date(lastCreatedAt)
    if (attrs.updatedAt) instance.updatedAt = new Date(lastCreatedAt)
  }
  Database.sequelize.addHook('beforeCreate', uniqueNow)
  Database.sequelize.addHook('beforeBulkCreate', (instances) => instances.forEach(uniqueNow))

  const emitted = []
  for (const method of SOCKET_METHODS) sinon.stub(SocketAuthority, method).callsFake((...args) => emitted.push({ method, args: jsonSafe(args) }))

  const watcherCalls = []
  for (const method of WATCHER_METHODS) sinon.stub(Watcher, method).callsFake((...args) => watcherCalls.push({ method, args: jsonSafe(args) }))

  const apiCacheManager = new ApiCacheManager()
  apiCacheManager.init(Database)
  const fakeServer = { auth: new Auth(), apiCacheManager }

  // Server.js loads Auth (and so TokenManager) before Database. Test files load Database first, so the TokenManager that
  // Auth holds has the half-initialised circular Database export and any path touching Database.sessionModel (session
  // invalidation, password change) throws or hangs. Load a fresh TokenManager now that Database is complete, with a secret.
  const cachedTokenManager = require.cache[TOKEN_MANAGER_PATH]
  delete require.cache[TOKEN_MANAGER_PATH]
  const FreshTokenManager = require(TOKEN_MANAGER_PATH)
  require.cache[TOKEN_MANAGER_PATH] = cachedTokenManager
  fakeServer.auth.tokenManager = new FreshTokenManager()
  FreshTokenManager.TokenSecret = 'characterization-test-secret'

  // SocketAuthority.clients only exists after initialize()
  const savedClients = SocketAuthority.clients
  SocketAuthority.clients = {}
  for (const name of MANAGER_NAMES) fakeServer[name] = opts.managers?.[name] || unconfigured(name)
  const apiRouter = new ApiRouter(fakeServer)
  installCoverageHook()
  if (!allRoutes) allRoutes = listRoutes(apiRouter.router)

  const app = express()
  // same upload middleware and options as Server.js (multipart bodies -> req.files, temp files in <metadata>/tmp)
  app.use(cookieParser())
  app.use(fileUpload({ defCharset: 'utf8', defParamCharset: 'utf8', useTempFiles: true, tempFileDir: path.join(global.MetadataPath, 'tmp') }))
  app.use(express.urlencoded({ extended: true }))
  app.use(express.json({ limit: '10mb' }))
  // stub login: x-test-user: <username> authenticates as that user, like passport's jwt strategy sets req.user
  app.use('/api', async (req, res, next) => {
    const username = req.headers['x-test-user']
    const user = username ? await Database.userModel.findOne({ where: { username } }) : null
    if (!user) return res.sendStatus(401)
    req.user = await Database.userModel.getUserById(user.id)
    next()
  })
  app.use('/api', (req, res, next) => {
    res.on('finish', () => {
      if (!req.route) return
      const key = routeKey(req.method, req.route.path)
      if (!routeHits.has(key)) routeHits.set(key, new Set())
      routeHits.get(key).add(res.statusCode)
    })
    next()
  })
  app.use('/api', apiRouter.router)

  const server = await new Promise((resolve) => {
    const s = app.listen(0, '127.0.0.1', () => resolve(s))
  })
  const base = `http://127.0.0.1:${server.address().port}`

  const api = {
    app,
    apiRouter,
    emitted,
    /** Watcher calls recorded instead of starting real file watchers */
    watcherCalls,
    tmp,
    base,
    /**
     * @param {string} method
     * @param {string} url path incl. query, e.g. '/api/libraries?limit=5'
     * @param {{ as?: string, json?: any, form?: { fields?: Record<string,string>, files?: { name:string, filename:string, content:string|Buffer, type?:string }[] }, headers?: Record<string,string> }} [o]
     *   `as` = username to authenticate as (omit for 401); `form` sends multipart/form-data (uploads)
     * @returns {Promise<{ status:number, headers:Record<string,string>, body:any }>}
     */
    async request(method, url, o = {}) {
      const headers = { ...(o.headers || {}) }
      if (o.as) headers['x-test-user'] = o.as
      let body
      if (o.json !== undefined) {
        headers['content-type'] = 'application/json'
        body = JSON.stringify(o.json)
      }
      if (o.form) {
        body = new FormData()
        for (const [k, v] of Object.entries(o.form.fields || {})) body.append(k, v)
        for (const f of o.form.files || []) body.append(f.name, new Blob([f.content], { type: f.type || 'application/octet-stream' }), f.filename)
      }
      const res = await fetch(base + url, { method, headers, body, redirect: 'manual' })
      const text = await res.text()
      let parsed = text
      try {
        parsed = text ? JSON.parse(text) : null
      } catch {}
      return { status: res.status, headers: { 'content-type': res.headers.get('content-type') }, body: parsed }
    },
    seed: {
      /** root, admin, user, guest users (username = type name) */
      async users() {
        const make = async (username, type, tweak) => {
          const permissions = Database.userModel.getDefaultPermissionsForUserType(type)
          if (tweak) tweak(permissions)
          return Database.userModel.create({ username, pash: 'hash', token: `token-${username}`, type, isActive: true, permissions, bookmarks: [], extraData: { seriesHideFromContinueListening: [] } })
        }
        return { root: await make('root', 'root'), admin: await make('admin', 'admin'), user: await make('user', 'user'), guest: await make('guest', 'guest') }
      }
    },
    async stop() {
      await new Promise((resolve) => server.close(resolve))
      sinon.restore()
      FreshTokenManager.TokenSecret = null
      SocketAuthority.clients = savedClients
      // CacheManager is a singleton holding paths inside the temp dir deleted below; back to its constructor state
      CacheManager.CachePath = CacheManager.CoverCachePath = CacheManager.ImageCachePath = CacheManager.ItemCachePath = null
      await Database.sequelize.close()
      for (const [k, v] of Object.entries(saved)) {
        if (v === undefined) delete global[k]
        else global[k] = v
      }
      fs.rmSync(tmp, { recursive: true, force: true })
    }
  }
  return api
}

module.exports = { startApi }
